"""Add t1 table

Revision ID: 82d366f633f7
Revises: 
Create Date: 2022-04-28 15:21:00.275810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d366f633f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t1',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('v', sa.Integer(), nullable=True),
    sa.Column('d', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t1')
    # ### end Alembic commands ###
