version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      # default username: postgres
      # password
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8900:8080
