/*
 * Query - filtered
 */

-- setup
DROP TABLE IF EXISTS t1;
CREATE TABLE IF NOT EXISTS t1 (
    x integer
);

INSERT INTO t1 VALUES (11);
INSERT INTO t1 VALUES (22);
INSERT INTO t1 VALUES (33);
INSERT INTO t1 VALUES (44);
INSERT INTO t1 VALUES (55);
INSERT INTO t1 VALUES (66);
INSERT INTO t1 VALUES (77);
INSERT INTO t1 VALUES (88);
INSERT INTO t1 VALUES (99);

-- main start

SELECT * FROM t1 WHERE x >= 55;

-- main end

-- cleanup
DROP TABLE IF EXISTS t1;