
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;

CREATE TABLE IF NOT EXISTS t1 (
    a int
);

CREATE TABLE IF NOT EXISTS t2 (
    b int
);

INSERT INTO t1 VALUES (11), (22), (33), (44), (55);

INSERT INTO t2 VALUES (22), (44);

-- title: t1 if any in t2 (bef)
SELECT * FROM t1
WHERE a > (SELECT b FROM t2);


DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
