
DROP TABLE IF EXISTS t1;

CREATE TABLE IF NOT EXISTS t1 (
    a int CHECK (a < 100)
);

INSERT OR IGNORE INTO t1 VALUES (11);
INSERT OR IGNORE INTO t1 VALUES (22);
INSERT OR IGNORE INTO t1 VALUES (99);
INSERT OR IGNORE INTO t1 VALUES (100);  -- does not make it
INSERT OR IGNORE INTO t1 VALUES (177);  -- does not make it

SELECT * FROM t1;

DROP TABLE IF EXISTS t1;
