DROP TABLE IF EXISTS t1;

CREATE TABLE IF NOT EXISTS t1 (
	pk NOT NULL,
	x,

	CONSTRAINT t1_pk PRIMARY KEY (pk)
);

INSERT INTO t1(pk, x) VALUES (1, 11);
INSERT INTO t1(pk, x) VALUES (2, 22);
INSERT INTO t1(pk, x) VALUES (3, 33);
INSERT INTO t1(pk, x) VALUES (2, 44);  -- should fail

SELECT * FROM t1;

DROP TABLE IF EXISTS t1;
