# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: something.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='something.proto',
  package='gandalf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fsomething.proto\x12\x07gandalf\"\x81\x02\n\x05Thing\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x01p\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x10\n\x03\x62la\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\'\n\x04gags\x18\x04 \x03(\x0b\x32\x19.gandalf.Thing.InnerThang\x1aN\n\nInnerThang\x12\x0b\n\x03val\x18\x01 \x01(\x03\x12+\n\x03kek\x18\x02 \x01(\x0e\x32\x19.gandalf.Thing.PotatoTypeH\x00\x88\x01\x01\x42\x06\n\x04_kek\"1\n\nPotatoType\x12\x07\n\x03RED\x10\x00\x12\t\n\x05WHITE\x10\x01\x12\x0f\n\x0bTRANSPARENT\x10\x63\x42\x08\n\x06_titleB\x04\n\x02_pB\x06\n\x04_bla\"\x14\n\x04That\x12\x0c\n\x04vals\x18\x01 \x03(\x05\x62\x06proto3'
)



_THING_POTATOTYPE = _descriptor.EnumDescriptor(
  name='PotatoType',
  full_name='gandalf.Thing.PotatoType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRANSPARENT', index=2, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=213,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_THING_POTATOTYPE)


_THING_INNERTHANG = _descriptor.Descriptor(
  name='InnerThang',
  full_name='gandalf.Thing.InnerThang',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='gandalf.Thing.InnerThang.val', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kek', full_name='gandalf.Thing.InnerThang.kek', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_kek', full_name='gandalf.Thing.InnerThang._kek',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=133,
  serialized_end=211,
)

_THING = _descriptor.Descriptor(
  name='Thing',
  full_name='gandalf.Thing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='gandalf.Thing.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='gandalf.Thing.p', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bla', full_name='gandalf.Thing.bla', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gags', full_name='gandalf.Thing.gags', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_THING_INNERTHANG, ],
  enum_types=[
    _THING_POTATOTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_title', full_name='gandalf.Thing._title',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_p', full_name='gandalf.Thing._p',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_bla', full_name='gandalf.Thing._bla',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=29,
  serialized_end=286,
)


_THAT = _descriptor.Descriptor(
  name='That',
  full_name='gandalf.That',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vals', full_name='gandalf.That.vals', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=308,
)

_THING_INNERTHANG.fields_by_name['kek'].enum_type = _THING_POTATOTYPE
_THING_INNERTHANG.containing_type = _THING
_THING_INNERTHANG.oneofs_by_name['_kek'].fields.append(
  _THING_INNERTHANG.fields_by_name['kek'])
_THING_INNERTHANG.fields_by_name['kek'].containing_oneof = _THING_INNERTHANG.oneofs_by_name['_kek']
_THING.fields_by_name['gags'].message_type = _THING_INNERTHANG
_THING_POTATOTYPE.containing_type = _THING
_THING.oneofs_by_name['_title'].fields.append(
  _THING.fields_by_name['title'])
_THING.fields_by_name['title'].containing_oneof = _THING.oneofs_by_name['_title']
_THING.oneofs_by_name['_p'].fields.append(
  _THING.fields_by_name['p'])
_THING.fields_by_name['p'].containing_oneof = _THING.oneofs_by_name['_p']
_THING.oneofs_by_name['_bla'].fields.append(
  _THING.fields_by_name['bla'])
_THING.fields_by_name['bla'].containing_oneof = _THING.oneofs_by_name['_bla']
DESCRIPTOR.message_types_by_name['Thing'] = _THING
DESCRIPTOR.message_types_by_name['That'] = _THAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Thing = _reflection.GeneratedProtocolMessageType('Thing', (_message.Message,), {

  'InnerThang' : _reflection.GeneratedProtocolMessageType('InnerThang', (_message.Message,), {
    'DESCRIPTOR' : _THING_INNERTHANG,
    '__module__' : 'something_pb2'
    # @@protoc_insertion_point(class_scope:gandalf.Thing.InnerThang)
    })
  ,
  'DESCRIPTOR' : _THING,
  '__module__' : 'something_pb2'
  # @@protoc_insertion_point(class_scope:gandalf.Thing)
  })
_sym_db.RegisterMessage(Thing)
_sym_db.RegisterMessage(Thing.InnerThang)

That = _reflection.GeneratedProtocolMessageType('That', (_message.Message,), {
  'DESCRIPTOR' : _THAT,
  '__module__' : 'something_pb2'
  # @@protoc_insertion_point(class_scope:gandalf.That)
  })
_sym_db.RegisterMessage(That)


# @@protoc_insertion_point(module_scope)
